#!/bin/bash

fuction install_lightdm(){
  pacman -Sy --noconfirm lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings
  systemctl enable lightdm.service
  
function install_gdm(){
  pacman -Sy --noconfirm gdm
  systemctl enable gdm.service}
  
function install_slim(){
  pacman -Sy --noconfirm slim
  systemctl enable slim.service}
  
function install_sddm(){
  pacman -Sy --noconfirm sddm
  systemctl enable sddm.service}
  
clear
echo "ESCOLHA QUAL DISPLAY MANAGER DESEJA INSTALAR:"
echo ""
echo "1 LIGHTDM"
echo "2 GDM"
echo "3 SDDM"
read dm
if $dm=1 then clear install_lightdm
if $dm=2 then clear install_gdm
if $dm=3 then clear install_sddm
done
