#!/bin/bash
function configura_local(){
  echo -e "pt_BR.UTF-8 UTF-8\npt_BR ISO-8859-1" > /etc/locale.gen 
  locale-gen && export LANG=pt_BR.UTF-8
  locale > /etc/locale.conf
  echo LOCAL CONFIGURADO COM SUSESSO! }
  
function instalar_grub(){
  pacman -Sy grub efibootmgr --noconfirm
  grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=arch /dev/sda }

echo DIGITE A SENHA PARA O USUÁRIO ROOT
passwd root
sleep 1
echo
echo DEFINA O HOSTNAME DA MÁQUINA:
read hostname
echo $hostname > /etc/hostname
sleep 1
echo
echo CONFIGURANDO LOCAL
function configura_local
sleep 1
echo
echo CONFIGURAR PACMAN.CONF
sleep 1
nano /etc/pacman.conf
pacman -Sy
sleep 1
echo
echo GERANDO IMAGEM INITRAMFS
sleep 1
pacman -S linux-lts
mkinitcpio -p linux-lts
sleep 1
echo
echo
echo INSTALANDO GRUB
sleep 1

sleep 1
echo
echo
echo CONFIGURANDO GRUB
sleep 1
grub-mkconfig -o /boot/grub/grub.cfg
sleep 1
echo
echo HABILITANDO SERVIÇO DHCP
echo
sleep 1
systemctl enable dhcpcd.service
echo -e "INSTALAÇÃO CONCLUÍDA COM SUSESSO!\nPRESSIONE 'CTRL + D' OU DIGITE EXIT PARA SAIR."
