#!/bin/bash
mkdir -p /var/lib/samba/usershare
groupadd -r sambashare
gpasswd sambashare -a $USER
chown root:sambashare /var/lib/samba/usershare
chmod 1770 /var/lib/samba/usershare
clear
echo "ADICIONE O SEGUINTE CONTEÚDO AO SMB.CONF:"
echo ""
echo "[global]"
echo "usershare path = /var/lib/samba/usershare"
echo "usershare max shares = 100"
echo "usershare allow guests = yes"
echo "usershare owner only = yes"
echo ""
echo""
echo "REINICIANDO SERVICOS SAMBA"
systemctl restart smbd.service
systemctl restart nmbd.service
sleep 2
clear
echo "Voce deve fazer logoff para que as alteracoes entrem em vigor"
