#!/bin/bash
pacman -Sy firefox firefox-i18n-pt-br gparted mplayer smplayer clementine gstreamer gst-libav gst-plugins-bad gst-plugins-base gst-plugins-good gst-plugins-ugly &&
sleep 1
echo "COMANDO CONCLUÍDO COM SUCESSO!"
