#!/bin/bash
pacman -Sy &&
pacman -S open-vm-tools xf86-video-vmware &&
cat /proc/version > /etc/arch-release &&
echo needs_root_rights=yes > /etc/X11/Xwrapper.config &&
systemctl start vmtoolsd.service
