#!/bin/bash
pacman -Sy xfce4 xfce4-whiskermenu-plugin xfce4-notifyd lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings networkmanager network-manager-applet &&
systemctl disable dhcpcd.service
systemctl enable NetworkManager.service &&
systemctl enable lightdm.service &&
sleep 1
echo COMANDO CONCLUÍDO COM SUCESSO!
